[versions]
kotlin = "2.2.21" # NOTE: Do NOT forget to update KSP version as well
kotlin-ksp = "2.2.21-2.0.4"
core-ktx = "1.17.0"
appcompat = "1.7.1"

dagger = "2.57.2"

firebase-bom = "34.6.0"

annotation = "1.9.1"
constraintlayout = "2.2.1"
fragment-ktx = "1.8.9"
lifecycle-extensions = "2.2.0"
lifecycle-viewmodel-ktx = "2.9.4"
navigation = "2.9.6"
preference-ktx = "1.2.1"
room = "2.8.3"
viewpager2 = "1.1.0"
material = "1.13.0"
browser = "1.9.0"

compose = "1.11.0"
compose-bom = "2025.11.00"
material3-android = "1.4.0"

gson = "2.13.2"
retrofit = "3.0.0"
okhttp = "5.3.0"
speedviewlib = "1.6.1"
threetenabp = "1.4.9"

usb-serial-for-android = "3.9.0"

junit = "4.13.2"
androidx-junit = "1.3.0"
espresso-core = "3.7.0"
runtime-livedata = "1.7.6"


[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk7", version.ref = "kotlin" }

core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
usb-serial-for-android = { module = "com.github.mik3y:usb-serial-for-android", version.ref = "usb-serial-for-android" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }


navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle-viewmodel-ktx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-viewmodel-ktx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }

androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }

material = { module = "com.google.android.material:material", version.ref = "material" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }


androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling"}
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose" }
compose-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata"}
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }

dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger" }
dagger-hilt-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "dagger" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp"}
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

speedviewlib = { module = "com.github.anastr:speedviewlib", version.ref = "speedviewlib" }

threetenabp = { module = "com.jakewharton.threetenabp:threetenabp", version.ref = "threetenabp" }

junit = { module = "junit:junit", version.ref = "junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3-android" }


[plugins]
kotlin-ksp-plugin = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlin-android =  { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
dagger-hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
room-plugin = { id = "androidx.room", version.ref = "room" }


